---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fio
  namespace: fio-test
  labels:
    app: fio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fio
  template:
    metadata:
      labels:
        app: fio
    spec:
      containers:
      - name: fio
        image: joshuarobinson/fio:3.19
        command: ["sh"]
        args: ["-c", "echo ${HOSTNAME} && mkdir -p /scratch/${HOSTNAME} && fio /configs/fio.job --eta=never --directory=/scratch/${HOSTNAME}"]
        volumeMounts:
        - name: fio-config-vol
          mountPath: /configs
        - name: fio-data
          mountPath: /scratch
        imagePullPolicy: Always
      restartPolicy: Always
      volumes:
      - name: fio-config-vol
        configMap:
          name: fio-job-config
      - name: fio-data
        persistentVolumeClaim:
          claimName: fio-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fio-claim
  namespace: fio-test
spec:
  storageClassName: px-db
#  storageClassName: pure-file
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
