---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fio
  namespace: fio-test
spec:
  serviceName: fio
  replicas: 3 
  selector:
    matchLabels:
      app: fio
  template:
    metadata:
      labels:
        app: fio
    spec:
      containers:
      - name: fio
        image: joshuarobinson/fio:3.19
        command: ["fio"]
        args: ["/configs/fio.job", "--eta=never", "--filename_format=$jobnum.$filenum", "--directory=/scratch/"]
        volumeMounts:
        - name: fio-config-vol
          mountPath: /configs
        - name: fio-data
          mountPath: /scratch
      volumes:
      - name: fio-config-vol
        configMap:
          name: fio-job-config
  volumeClaimTemplates:
  - metadata:
      name: fio-data
    spec:
#      storageClassName: pure-block
      storageClassName: longhorn
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 40Gi
