apiVersion: v1
data:
  fio.job: |-
    [global]
    direct=1
    iodepth=8
    numjobs=50
    size=1G
    nrfiles=10
    norandommap
    rw=randrw
    ramp_time=30
    group_reporting
    [firstjob]
    ioengine=psync
    time_based=1
    runtime=180
    bs=512K
    [secondjob]
    ioengine=libaio
    time_based=1
    runtime=180
    bs=128K
